services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile

    image: ralik100/sysag:client_v1

    volumes:
      - /tmp/metrics.sock:/tmp/metrics.sock

  postgres:
    image: postgres:16-alpine


  redis:
    image: redis:alpine