"""
SysmonAgent Logger Module

Responsible for asynchronous event persistence.

Events generated by collectors and heartbeat threads are first
placed into an in-memory queue. A dedicated logger thread reads
events from the queue, enriches them with timestamps and writes
them to disk in configurable batches.

This design reduces disk I/O overhead and prevents monitoring
operations from being blocked by file system writes.
"""

import json
from pathlib import Path
import queue
import time
from datetime import datetime
import os


# Shared event queue used by collectors, heartbeat and logger.
# The queue acts as a buffer between event producers and the
# persistence layer.
q = queue.Queue(maxsize=1000)

# File handle used by the logger thread.
_file = None


def init(log_file):
    """
    Initializes the logging subsystem.

    Creates the output directory if it does not exist and opens
    the configured log file in append mode.

    Args:
        log_file (str):
            Name of the output log file.

    Raises:
        OSError:
            If the log directory or file cannot be created.
    """

    global _file

    filepath = Path("/output")

    try:
        os.mkdir(filepath)
        print("Path created successfully")
    except FileExistsError:
        print(f"{filepath} already exists")

    filepath = Path("/output") / log_file

    _file = open(filepath, "a")


def log(batch_size, flush_interval, statistics):
    """
    Main logger loop.

    Reads events from the queue, attaches timestamps,
    updates performance statistics and writes events
    to disk in batches.

    Events are flushed when:
    - batch_size is reached,
    - flush_interval expires,
    - logger shutdown is requested.

    Args:
        batch_size (int):
            Maximum number of events written in a single batch.

        flush_interval (int | float):
            Maximum number of seconds between batch writes.

        statistics:
            Statistics collector used for heartbeat metrics.

    Raises:
        RuntimeError:
            If the logger has not been initialized.
    """

    global _file

    batch = []

    while True:
        try:
            event = q.get(timeout=flush_interval)

        except queue.Empty:
            if batch:
                write_batch(batch)
                batch.clear()

            continue

        if event is None:
            q.task_done()
            break

        if _file is None:
            raise RuntimeError("Logger not initialized")

        timestamp = get_datetime()
        event["timestamp"] = timestamp

        batch.append(event)

        q.task_done()

        statistics.record_event()

        # Heartbeat events do not contain creation timestamps
        # used for processing latency measurements.
        if event["level"] != "HEARTBEAT":
            now = time.time()
            lag = now - event["created_at"]
            statistics.record_lag(lag)

        if len(batch) >= batch_size:
            write_batch(batch)
            batch.clear()

    # Flush remaining events before shutdown.
    if batch:
        write_batch(batch)
        batch.clear()

    # Close the log file during graceful shutdown.
    if _file:
        _file.close()
        _file = None


def get_datetime():
    """
    Returns current UTC timestamp in ISO-8601 format.

    Returns:
        str:
            Current UTC timestamp with Z suffix.
    """

    current_utc_datetime = datetime.utcnow()
    current_utc_iso_datetime = current_utc_datetime.isoformat() + "Z"

    return current_utc_iso_datetime


def write_batch(batch):
    """
    Persists a batch of events to the log file.

    Each event is serialized as a single JSON document
    and written as a separate line.

    Args:
        batch (list[dict]):
            Collection of events to be written.
    """

    global _file

    for event in batch:
        _file.write(json.dumps(event) + "\n")

    _file.flush()


def close():
    """
    Requests graceful logger shutdown.

    A sentinel value is placed into the queue.
    When received by the logger thread, the logging
    loop terminates after flushing remaining events.
    """

    q.put(None)
