"""
SysmonAgent Telemetry Module

Provides runtime statistics used by the heartbeat subsystem.

The Telemetry class collects information about:

- processed events,
- application errors,
- event processing delays,
- queue utilization,
- application uptime.

Collected metrics are periodically exposed through heartbeat
events, allowing administrators to monitor the health and
performance of the monitoring system itself.
"""

import threading
import time
from collections import deque


class Telemetry:
    """
    Thread-safe runtime telemetry collector.

    The class aggregates operational metrics generated by
    various application components.

    Statistics are continuously updated during runtime and
    periodically exported through heartbeat events.

    Attributes:
        lock (threading.Lock):
            Synchronization primitive protecting shared state.

        events_processed (int):
            Total number of processed events.

        errors (int):
            Total number of runtime errors.

        lags (deque):
            Sliding window containing recent event processing
            delays.

        max_lag (float):
            Highest observed processing delay.

        start_time (float):
            Application startup timestamp.
    """

    def __init__(self, lag_window=100):
        """
        Creates a new telemetry collector.

        Args:
            lag_window (int):
                Maximum number of recent lag measurements
                stored for average lag calculations.
        """

        self.lock = threading.Lock()

        self.events_processed = 0
        self.errors = 0

        # Stores recent event processing delays.
        self.lags = deque(maxlen=lag_window)

        # Highest delay observed since startup.
        self.max_lag = 0.0

        # Application startup timestamp.
        self.start_time = time.time()

    # ---------- UPDATE METHODS ----------

    def record_event(self):
        """
        Records a successfully processed event.

        Called by the logger after an event has been accepted
        for processing.
        """

        with self.lock:
            self.events_processed += 1

    def record_error(self):
        """
        Records an application error.

        Called whenever an exception is encountered during
        collector execution or other monitored operations.
        """

        with self.lock:
            self.errors += 1

    def record_lag(self, lag):
        """
        Records event processing latency.

        Lag is defined as the time difference between
        event creation and event persistence.

        Args:
            lag (float):
                Processing delay expressed in seconds.
        """

        with self.lock:

            self.lags.append(lag)

            if lag > self.max_lag:
                self.max_lag = lag

    # ---------- SNAPSHOT ----------

    def snapshot(self, queue_size, queue_capacity):
        """
        Creates a heartbeat snapshot containing current
        application telemetry.

        The returned structure is used directly by the
        heartbeat subsystem and later persisted by the logger.

        Args:
            queue_size (int):
                Current number of events waiting in the queue.

            queue_capacity (int):
                Maximum queue capacity.

        Returns:
            dict:
                Complete heartbeat event containing:

                - uptime information,
                - performance metrics,
                - queue statistics,
                - error statistics.
        """

        with self.lock:

            # Time elapsed since application startup.
            uptime = time.time() - self.start_time

            # Average processing lag calculated from
            # recent measurements.
            if self.lags:
                avg_lag = sum(self.lags) / len(self.lags)
            else:
                avg_lag = 0.0

            # Average event throughput.
            eps = (
                self.events_processed / uptime
                if uptime > 0
                else 0.0
            )

            # Queue utilization ratio.
            utilization = (
                queue_size / queue_capacity
                if queue_capacity > 0
                else 0.0
            )

            return {
                "level": "HEARTBEAT",

                # Seconds since startup.
                "uptime": uptime,

                "performance": {

                    # Total processed events.
                    "events_processed":
                        self.events_processed,

                    # Average events processed per second.
                    "events_per_sec":
                        eps,

                    # Average observed event delay.
                    "avg_lag":
                        avg_lag,

                    # Highest observed event delay.
                    "max_lag":
                        self.max_lag,
                },

                "queue": {

                    # Current queue size.
                    "size":
                        queue_size,

                    # Maximum queue capacity.
                    "capacity":
                        queue_capacity,

                    # Queue utilization ratio.
                    "utilization":
                        utilization,
                },

                "errors": {

                    # Total number of errors observed
                    # since startup.
                    "total":
                        self.errors,
                }
            }